"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";

export default function EditTournamentPage() {
  const { id } = useParams<{ id: string }>();
  const router = useRouter();
  const [item, setItem] = useState<{ owner: string } | null>(null);
  const [name, setName] = useState(""); const [gameType, setGameType] = useState(""); const [password, setPassword] = useState(""); const [noPassword, setNoPassword] = useState(false); const [rounds, setRounds] = useState("4"); const [pairingMode, setPairingMode] = useState(""); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  useEffect(() => { Promise.all([fetch("/api/profile"), fetch(`/api/tournaments?id=${encodeURIComponent(id)}`)]).then(async ([profileResponse, tournamentResponse]) => { const profile = profileResponse.ok ? await profileResponse.json() as { nickname?: string } : {}; const tournament = tournamentResponse.ok ? await tournamentResponse.json() as { owner: string; phase: string; name: string; gameType: string; passwordRequired?: boolean; rounds: number; pairingMode: string; notice?: string } : null; if (!tournament || tournament.owner !== profile.nickname || tournament.phase !== "before") throw new Error("開催前の大会で、作成者本人のみ編集できます。"); setItem(tournament); setName(tournament.name); setGameType(tournament.gameType); setPassword(""); setNoPassword(!tournament.passwordRequired); setRounds(String(tournament.rounds)); setPairingMode(tournament.pairingMode); setNotice(tournament.notice ?? ""); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "大会データを取得できませんでした。")); }, [id]);
  const submit = async (event: FormEvent) => { event.preventDefault(); const response = await fetch("/api/tournaments", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, name, gameType, password: noPassword ? "" : (password.trim() || undefined), rounds: Number(rounds), pairingMode, notice }) }); const payload = await response.json().catch(() => null) as { ok?: boolean; error?: string } | null; if (response.ok && payload?.ok) router.push("/"); else setError(payload?.error ?? "保存に失敗しました"); };
  return <main className="jm-user-shell jm-narrow"><Link className="jm-back" href="/">← 大会一覧</Link><p className="janmatch-kicker">TOURNAMENT SETTINGS</p><h1>大会を編集</h1>{error ? <p className="jm-error">{error}</p> : item && <form className="jm-form-card jm-create-form" onSubmit={(event) => void submit(event)}><p>主催者：{item.owner}</p><label>大会名<input value={name} onChange={event => setName(event.target.value)} /></label><label>ゲームの種類<input value={gameType} onChange={event => setGameType(event.target.value)} /></label><label>参加パスワード<input type="text" value={password} disabled={noPassword} onChange={event => setPassword(event.target.value)} placeholder={noPassword ? "パスワードなし" : "変更しない場合は再入力"} /></label><label className="jm-check-label"><input type="checkbox" checked={noPassword} onChange={event => setNoPassword(event.target.checked)} /> パスワードなしで参加可能にする</label><label>全回戦数<input type="number" value={rounds} min={1} max={20} onChange={event => setRounds(event.target.value)} /></label><label>組み合わせ方式<input value={pairingMode} onChange={event => setPairingMode(event.target.value)} /></label><label>ルール・お知らせ<textarea value={notice} onChange={event => setNotice(event.target.value)} /></label><button className="jm-primary">変更を保存</button></form>}</main>;
}
