"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Phase = "before" | "active" | "ended";
type Tournament = { id: string; name: string; gameType?: string; date?: string; startAt?: string; rounds: number; status: string; color: string; pairingMode?: string; phase?: Phase; owner?: string };
const phaseLabels: { value: Phase; label: string }[] = [{ value: "before", label: "開催前" }, { value: "active", label: "開催中" }, { value: "ended", label: "終了" }];
function normalizePhase(t: Tournament): Phase { if (t.phase) return t.phase; if (t.status === "終了") return "ended"; if (t.status === "開催中") return "active"; return "before"; }

export default function TournamentListPage() {
  const [tournaments, setTournaments] = useState<Tournament[]>([]); const [selected, setSelected] = useState<Phase[]>(["before", "active"]); const [currentNickname, setCurrentNickname] = useState(""); const [authenticated, setAuthenticated] = useState(false);
  useEffect(() => { let active = true; Promise.all([fetch("/api/tournaments"), fetch("/api/profile"), fetch("/api/auth/me")]).then(async ([tournamentsResponse, profileResponse, authResponse]) => { if (!tournamentsResponse.ok) throw new Error(); const remote = await tournamentsResponse.json() as Tournament[]; const profile = profileResponse.ok ? await profileResponse.json() as { nickname?: string } : {}; if (active) { setTournaments(remote.map((t) => ({ ...t, date: t.date ?? t.startAt, status: t.status ?? ({ before: "開催前", active: "開催中", ended: "終了" } as Record<string, string>)[t.phase ?? "before"] }))); setCurrentNickname(profile.nickname ?? ""); setAuthenticated(authResponse.ok); } }).catch(() => { if (active) { setTournaments([]); setCurrentNickname(""); setAuthenticated(false); } }); return () => { active = false; }; }, []);
  const visible = useMemo(() => tournaments.filter((t) => selected.includes(normalizePhase(t))), [selected, tournaments]); const toggle = (phase: Phase) => setSelected((current) => current.includes(phase) ? current.filter((item) => item !== phase) : [...current, phase]);
  return <main className="jm-user-shell"><header className="jm-user-header"><div><p className="janmatch-kicker">JANMATCH</p><h1>大会一覧</h1><p>参加する大会を選ぶか、新しい大会を作成します。</p></div><nav><Link className="jm-create-link" href="/tournaments/new">＋ 大会を作成</Link><Link href={authenticated ? "/profile" : "/login"}>{authenticated ? "プロフィール設定" : "Discordでログイン"}</Link></nav></header>{!authenticated && <section className="jm-profile-hint"><strong>はじめての方へ</strong><span>Discordでログインしてプロフィールを設定してください。</span><Link href="/login">ログインする →</Link></section>}<div className="jm-list-toolbar"><p className="janmatch-kicker">TOURNAMENTS</p><div className="jm-phase-filters">{phaseLabels.map((phase) => <button key={phase.value} className={selected.includes(phase.value) ? "selected" : ""} onClick={() => toggle(phase.value)}>{phase.label}</button>)}</div></div><section className="jm-tournament-grid">{visible.map((tournament) => <article className="jm-tournament-card" key={tournament.id}><div className={`jm-tournament-accent ${tournament.color}`} /><div className="jm-card-body"><div className="jm-card-meta"><span className="jm-status">{tournament.status}</span><span>{tournament.date}</span></div><h2>{tournament.name}</h2><div className="jm-card-stats"><span>{tournament.gameType ?? "雀魂-じゃんたま-"}</span><span>全{tournament.rounds}回戦</span></div><p className="jm-card-pairing">組み合わせ：{tournament.pairingMode ?? "未設定"}</p><p className="jm-card-owner">主催者：{tournament.owner ?? "未設定"}</p><div className="jm-card-actions"><Link className="jm-action-join" href={`/tournaments/${tournament.id}`}>詳細</Link>{normalizePhase(tournament) === "before" && currentNickname && currentNickname === tournament.owner && <><Link className="jm-action-admin" href={`/tournaments/${tournament.id}/edit`}>編集</Link><Link className="jm-action-admin" href={`/tournaments/${tournament.id}/manage`}>管理</Link></>}</div></div></article>)}{visible.length === 0 && <div className="jm-list-empty">選択した状態の大会はありません。</div>}</section></main>;
}
