"use client";
import Link from "next/link"; import { useEffect, useMemo, useState } from "react"; import { useParams, useSearchParams } from "next/navigation";
type Table={label:string;members:string[];representative:string;roomId?:string;scores?:number[];approvals?:string[];resultStatus?:string}; type Round={status:string;tables:Table[]}; type Tournament={id:string;name:string;date?:string;startAt?:string;password?:string;rounds:number;notice?:string;owner?:string;gameType?:string;pairingMode?:string};
const fallback:Tournament={id:"janmatch-01",name:"第1回 JanMatch交流戦",date:"2026年10月12日（月）20:00開始",password:"JMP2026",rounds:4,notice:"東南戦／25000点持ち。",owner:"きたろう",gameType:"雀魂-じゃんたま-",pairingMode:"最終戦だけ順位卓"};
export default function TournamentPage(){const {id}=useParams<{id:string}>();const sp=useSearchParams();const [t,setT]=useState(fallback);const [nick,setNick]=useState("");const [pw,setPw]=useState("");const [open,setOpen]=useState(false);const [rounds,setRounds]=useState<Round[]>([]);const [entries,setEntries]=useState<boolean[]>([]);const [msg,setMsg]=useState("");const manage=sp.get("mode")==="manage";
useEffect(()=>{const n=localStorage.getItem("janmatch:nickname")??"";setNick(n);if(document.cookie.includes(`janmatch_access_${id}=1`))setOpen(true);fetch(`/api/tournaments?id=${id}`).then(r=>r.json()).then((f:Tournament)=>{const x=f||fallback;setT({...x,date:x.date??x.startAt});if(!x.password)setOpen(true);setRounds(Array.from({length:x.rounds},()=>({status:"受付前",tables:[]})));fetch(`/api/tournaments/entries?tournamentId=${id}&nickname=${encodeURIComponent(n)}`).then(r=>r.ok?r.json():[]).then((rows:any[])=>setEntries(Array.from({length:x.rounds},(_,i)=>Boolean(rows.find(v=>v.round===i+1)?.joined))));}).catch(()=>setRounds(Array.from({length:fallback.rounds},()=>({status:"受付前",tables:[]}))));},[id]);
const save=(v:Round[])=>{setRounds(v);localStorage.setItem(`janmatch:rounds:${id}`,JSON.stringify(v));};const toggle=async(i:number)=>{const v=entries.map((x,j)=>j===i?!x:x);setEntries(v);await fetch("/api/tournaments/entries",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({tournamentId:id,nickname:nick,round:i+1,joined:v[i]})});};const joinCount=useMemo(()=>entries.filter(Boolean).length,[entries]);
const approve=(ri:number,ti:number,table:Table)=>{const a=[...(table.approvals??[]),nick].filter((v,i,x)=>v&&x.indexOf(v)===i);const status=a.length>=table.members.length?"結果確定":"結果登録済み（承認待ち）";save(rounds.map((r,i)=>i===ri?{...r,tables:r.tables.map((x,j)=>j===ti?{...x,approvals:a,resultStatus:status}:x)}:r));};
const unlock=()=>{if(!t.password||pw===t.password){document.cookie=`janmatch_access_${id}=1; max-age=10368000; path=/; samesite=lax`;setOpen(true);}else setMsg("パスワードが違います");};
return <main className="jm-user-shell jm-narrow"><Link className="jm-back" href="/">← 大会一覧</Link><div className="jm-detail-title"><div><span className="jm-status">開催前</span><h1>{t.name}</h1><p>{t.date}</p><p className="jm-card-owner">主催者：{t.owner}</p></div><Link href="/profile" className="jm-outline">ニックネーム変更</Link></div>{!open?<section className="jm-lock-card"><h2>参加用パスワードを入力</h2><div className="jm-password-row"><input type="password" value={pw} onChange={e=>setPw(e.target.value)}/><button className="jm-primary" onClick={unlock}>大会を開く</button></div>{msg&&<p className="jm-error">{msg}</p>}</section>:<section className="jm-detail-card"><div className="jm-round-head"><h2>{manage?"受付・卓組み管理":"回戦受付"}</h2>{!manage&&<span>{joinCount}/{t.rounds}回戦 参加</span>}</div>{rounds.map((r,ri)=><div className="jm-round-block" key={ri}><h3>{ri+1}回戦 <small>{r.status}</small></h3>{manage&&r.status==="受付前"&&<button className="jm-primary" onClick={()=>save(rounds.map((x,i)=>i===ri?{...x,status:"受付中"}:x))}>受付開始（60秒）</button>}{manage&&r.status==="受付中"&&<button className="jm-primary" onClick={()=>save(rounds.map((x,i)=>i===ri?{...x,status:"確定",tables:[]}:x))}>参加者を確定</button>}{!manage&&<button className={entries[ri]?"joined":""} onClick={()=>toggle(ri)}>{entries[ri]?"参加登録を取り消す":"参加登録"}</button>}{r.tables.map((table,ti)=><div className="jm-table-row" key={table.label}><b>{table.label}</b><span>{table.members.join("・")}</span><small>代表者：{table.representative}{table.roomId?` / ルームID：${table.roomId}`:""}</small>{table.scores&&<small>{table.scores.join(" / ")}　{table.resultStatus}</small>}{!manage&&table.scores&&table.members.includes(nick)&&table.resultStatus!=="結果確定"&&<button onClick={()=>approve(ri,ti,table)}>結果承認</button>}</div>)}</div>)}</section>}</main>}
