"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useParams, useSearchParams } from "next/navigation";

type Table = { label: string; members: string[]; representative: string; roomId?: string; scores?: number[] };
type Round = { status: "受付前" | "受付中" | "確定"; deadline?: number; tables: Table[] };
type Tournament = { id: string; name: string; date?: string; startAt?: string; password?: string; rounds: number; notice?: string; owner?: string; gameType?: string; pairingMode?: string; uma?: number[] };
const fallback: Tournament = { id: "janmatch-01", name: "第1回 JanMatch交流戦", date: "2026年10月12日（月）20:00開始", password: "JMP2026", rounds: 4, notice: "東南戦／25000点持ち。", owner: "きたろう", gameType: "雀魂-じゃんたま-", pairingMode: "最終戦だけ順位卓" };

export default function TournamentPage() {
  const { id } = useParams<{ id: string }>(); const searchParams = useSearchParams(); const [tournament, setTournament] = useState(fallback); const [nickname, setNickname] = useState(""); const [password, setPassword] = useState(""); const [unlocked, setUnlocked] = useState(false); const [rounds, setRounds] = useState<Round[]>([]); const [entries, setEntries] = useState<boolean[]>([]); const [message, setMessage] = useState("");
  useEffect(() => { const nick = window.localStorage.getItem("janmatch:nickname") ?? ""; setNickname(nick); if (document.cookie.split("; ").some((cookie) => cookie === `janmatch_access_${id}=1`)) setUnlocked(true); fetch(`/api/tournaments?id=${encodeURIComponent(id)}`).then((response) => response.ok ? response.json() : Promise.reject()).then((found: Tournament | null) => { const t = found ? { ...found, date: found.date ?? found.startAt } : fallback; setTournament(t); if (!t.password) setUnlocked(true); setRounds(Array.from({ length: t.rounds }, () => ({ status: "受付前", tables: [] }))); setEntries(Array.from({ length: t.rounds }, () => false)); }).catch(() => { setTournament(fallback); setRounds(Array.from({ length: fallback.rounds }, () => ({ status: "受付前", tables: [] }))); setEntries(Array.from({ length: fallback.rounds }, () => false)); }); }, [id]);
  const isOrganizer = searchParams.get("mode") === "manage" && nickname !== "" && nickname === tournament.owner; const currentRound = rounds.findIndex((round) => round.status !== "確定"); const joinedCount = useMemo(() => entries.filter(Boolean).length, [entries]);
  const saveRounds = (next: Round[]) => { setRounds(next); window.localStorage.setItem(`janmatch:rounds:${id}`, JSON.stringify(next)); };
  const toggleEntry = (index: number) => { const next = entries.map((v, i) => i === index ? !v : v); setEntries(next); window.localStorage.setItem(`janmatch:entries:${id}:${nickname}`, JSON.stringify(next)); };
  const start受付 = (index: number) => { if (index > 0 && rounds[index - 1]?.status !== "確定") { setMessage("前の回戦が完了してから開始できます"); return; } const next = rounds.map((r, i) => i === index ? { ...r, status: "受付中" as const, deadline: Date.now() + 60000 } : r); saveRounds(next); };
  const confirm受付 = (index: number) => { const names = Object.keys(localStorage).filter((key) => key.startsWith(`janmatch:entries:${id}:`)).map((key) => ({ name: key.split(":").pop()!, joined: JSON.parse(localStorage.getItem(key) ?? "[]")[index] })).filter((v) => v.joined).map((v) => v.name); const shuffled = [...new Set(names)].sort(() => Math.random() - 0.5); const tables: Table[] = []; for (let i = 0; i < shuffled.length; i += 4) { const members = shuffled.slice(i, i + 4); tables.push({ label: `${String.fromCharCode(65 + tables.length)}卓`, members, representative: members[0] }); } const next = rounds.map((r, i) => i === index ? { status: "確定" as const, tables } : r); saveRounds(next); };
  const setRoom = (roundIndex: number, tableIndex: number, roomId: string) => { const next = rounds.map((r, ri) => ri === roundIndex ? { ...r, tables: r.tables.map((t, ti) => ti === tableIndex ? { ...t, roomId } : t) } : r); saveRounds(next); };
  const setScores = (roundIndex: number, tableIndex: number, value: string) => { const scores = value.split(",").map((v) => Number(v.trim())); if (scores.length !== 4 || scores.some((v) => !Number.isFinite(v))) { setMessage("4人分をカンマ区切りで入力してください"); return; } if (scores.reduce((a, b) => a + b, 0) !== 1000) { setMessage("4人の合計が1000になるように入力してください"); return; } const next = rounds.map((r, ri) => ri === roundIndex ? { ...r, tables: r.tables.map((t, ti) => ti === tableIndex ? { ...t, scores } : t) } : r); saveRounds(next); setMessage("結果を登録しました"); };
  const unlock = () => { if (!(tournament.password ?? "") || password === tournament.password) { document.cookie = `janmatch_access_${id}=1; max-age=10368000; path=/; samesite=lax`; setUnlocked(true); setMessage("大会内容を確認できます（次回から入力不要）"); } else setMessage("パスワードが違います"); };
  return <main className="jm-user-shell jm-narrow"><Link className="jm-back" href="/">← 大会一覧</Link><div className="jm-detail-title"><div><span className="jm-status">{tournament.date.includes("開催中") ? "開催中" : "開催前"}</span><h1>{tournament.name}</h1><p>{tournament.date}</p><p className="jm-card-owner">主催者：{tournament.owner ?? "未設定"}</p></div><Link href="/profile" className="jm-outline">ニックネーム変更</Link></div>{!unlocked ? <section className="jm-lock-card"><h2>参加用パスワードを入力</h2><div className="jm-password-row"><input type="password" value={password} onChange={(e) => setPassword(e.target.value)} /><button className="jm-primary" onClick={unlock}>大会を開く</button></div>{message && <p className="jm-error">{message}</p>}</section> : <><section className="jm-detail-card"><p className="janmatch-kicker">ABOUT</p><h2>大会概要</h2><p>{tournament.gameType} / 全{tournament.rounds}回戦 / 組み合わせ：{tournament.pairingMode}</p><p>{tournament.notice}</p></section><section className="jm-detail-card"><div className="jm-round-head"><h2>回戦受付</h2><span>{joinedCount}/{tournament.rounds}回戦 参加</span></div>{rounds.map((round, index) => <div className="jm-round-block" key={index}><h3>{index + 1}回戦 <small>{round.status}</small></h3>{!isOrganizer && <button className={entries[index] ? "joined" : ""} onClick={() => toggleEntry(index)}>{entries[index] ? "参加登録済み" : "参加する"}</button>}{isOrganizer && round.status === "受付前" && <button className="jm-primary" onClick={() => start受付(index)}>受付開始（60秒）</button>}{isOrganizer && round.status === "受付中" && <button className="jm-primary" onClick={() => confirm受付(index)}>参加者を確定して卓決め</button>}{round.tables.map((table, ti) => <div className="jm-table-row" key={table.label}><b>{table.label}</b><span>{table.members.join("・")}</span><small>代表者：{table.representative}{table.roomId ? ` / ルームID：${table.roomId}` : ""}</small>{table.representative === nickname && <><input placeholder="ルームID" defaultValue={table.roomId} onBlur={(e) => setRoom(index, ti, e.target.value)} /><input placeholder="点数4人分（例: 250,250,250,250）" onBlur={(e) => setScores(index, ti, e.target.value)} /></>}</div>)}</div>)}{message && <p className="jm-success">{message}</p>}</section></>}</main>;
}
