"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";

type Table = { label: string; members: string[]; representative: string; roomId?: string; resultStatus?: string };
type Round = { round: number; status: string; deadline?: number; tables: Table[]; version: number };
type Tournament = { id: string; name: string; rounds: number; owner?: string; phase?: string; isOrganizer: boolean };

function toLocalInput(timestamp?: number) { if (!timestamp) return ""; const date = new Date(timestamp - new Date().getTimezoneOffset() * 60000); return date.toISOString().slice(0, 16); }
function fromLocalInput(value: string) { return new Date(value).getTime(); }
function formatDeadline(timestamp?: number) { return timestamp ? new Date(timestamp).toLocaleString("ja-JP") : "未設定"; }

export default function ManageTournamentPage() {
  const { id } = useParams<{ id: string }>();
  const [tournament, setTournament] = useState<Tournament | null>(null); const [rounds, setRounds] = useState<Round[]>([]); const [scheduled, setScheduled] = useState<Record<number, string>>({}); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => { const tournamentResponse = await fetch(`/api/tournaments?id=${encodeURIComponent(id)}`); const data = await tournamentResponse.json() as Tournament & { error?: string }; if (!tournamentResponse.ok || !data.isOrganizer) throw new Error(data.error ?? "主催者本人のみ大会を管理できます。"); const stateResponse = await fetch(`/api/tournaments/state?tournamentId=${encodeURIComponent(id)}`); const states = await stateResponse.json() as Round[] & { error?: string }; if (!stateResponse.ok) throw new Error(states.error ?? "回戦状態を取得できませんでした。"); setTournament(data); setRounds(states); setScheduled((current) => Object.fromEntries(states.map((round) => [round.round, current[round.round] || toLocalInput(round.deadline)]))); }, [id]);
  useEffect(() => { void load().catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "大会データを取得できませんでした。")); }, [load]);
  useEffect(() => { const timer = window.setInterval(() => { void load(); }, 5000); return () => window.clearInterval(timer); }, [load]);
  const mutate = async (round: Round, action: string, deadline?: number) => { const response = await fetch("/api/tournaments/state", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ tournamentId: id, round: round.round, expectedVersion: round.version, action, ...(deadline ? { deadline } : {}) }) }); const payload = await response.json() as Round & { error?: string }; if (!response.ok) { setMessage(payload.error ?? "回戦状態を更新できませんでした"); return; } setScheduled((current) => ({ ...current, [round.round]: action === "cancel_schedule" ? "" : toLocalInput(payload.deadline) })); setMessage(action === "confirm" ? `${round.round}回戦を確定しました` : action === "cancel_schedule" ? `${round.round}回戦の終了予約を取り消しました` : `${round.round}回戦の受付終了を予約しました`); await load(); };
  const totalTables = useMemo(() => rounds.reduce((sum, round) => sum + round.tables.length, 0), [rounds]);
  if (error) return <main className="jm-user-shell jm-narrow"><Link className="jm-back" href="/">← 大会一覧</Link><p className="jm-error">{error}</p></main>;
  if (!tournament) return <main className="jm-user-shell jm-narrow"><p>大会管理を読み込んでいます。</p></main>;
  return <main className="jm-user-shell jm-narrow"><Link className="jm-back" href={`/tournaments/${id}`}>← 大会詳細</Link><div className="jm-detail-title"><div><p className="janmatch-kicker">ORGANIZER CONSOLE</p><h1>大会管理</h1><p>{tournament.name}</p></div><Link className="jm-outline" href={`/tournaments/${id}/edit`}>大会設定</Link></div><section className="jm-detail-card"><h2>管理サマリー</h2><p>大会状態：<strong>{tournament.phase === "ended" ? "終了" : tournament.phase === "active" ? "開催中" : "開催前"}</strong> / 回戦：{rounds.length} / 確定卓：{totalTables}</p><p className="jm-form-note">ローカル運用では、予定時刻を過ぎた後の最初の状態取得時に自動で受付終了・卓組み確定します。</p></section><section className="jm-detail-card"><div className="jm-round-head"><h2>回戦管理</h2><span>5秒ごとに更新</span></div>{rounds.map((round) => <div className="jm-round-block" key={round.round}><h3>{round.round}回戦 <small>{round.status}</small></h3>{round.status === "受付前" && <button className="jm-primary" onClick={() => void mutate(round, "start", Date.now() + 60000)}>受付開始（60秒）</button>}{round.status === "受付中" && <><p className="jm-form-note">受付終了予定：{formatDeadline(round.deadline)}</p><div className="jm-manage-actions"><button className="jm-primary" onClick={() => void mutate(round, "confirm")}>今すぐ受付終了・卓組み確定</button><button onClick={() => void mutate(round, "schedule", Date.now() + 60000)}>60秒後に受付終了</button><button onClick={() => void mutate(round, "cancel_schedule")}>予定を取消</button></div><div className="jm-schedule-row"><input type="datetime-local" value={scheduled[round.round] ?? ""} onChange={(event) => setScheduled((current) => ({ ...current, [round.round]: event.target.value }))} /><button onClick={() => { const deadline = fromLocalInput(scheduled[round.round] ?? ""); if (Number.isFinite(deadline) && deadline > Date.now()) void mutate(round, "schedule", deadline); else setMessage("未来の日時を指定してください"); }}>指定時刻に予約</button></div></>}{round.status === "確定" && <><p className="jm-round-closed">卓組み確定済み</p>{round.tables.map((table) => <div className="jm-table-row" key={table.label}><b>{table.label}</b><span>{table.members.join("・") || "参加者なし"}</span><small>代表者：{table.representative || "未設定"}{table.roomId ? ` / ルームID：${table.roomId}` : ""}</small></div>)}</>}</div>)}{message && <p className="jm-success">{message}</p>}</section></main>;
}
